# Generated by Django 5.0.14 on 2026-05-15 00:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(7.0),
                        ],
                        verbose_name="nota",
                    ),
                ),
                (
                    "coefficient",
                    models.PositiveIntegerField(default=1, verbose_name="coeficiente"),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="fecha")),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="estudiante",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="courses.subject",
                        verbose_name="asignatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "nota",
                "verbose_name_plural": "notas",
            },
        ),
    ]
